# Generated by Django 3.2.16 on 2023-01-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minute',
            new_name='time_minutes',
        ),
    ]
