# Generated by Django 3.2.16 on 2023-01-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
