# Generated by Django 3.2.16 on 2023-01-24 14:24

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230124_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=base.models.recipe_image_file_path),
        ),
    ]
